ansible_user: "{{ lookup('ansible.builtin.env', 'SERVER_ADMIN_USER') }}"
ansible_password: "{{ lookup('ansible.builtin.env', 'SERVER_ADMIN_PASSWORD') }}"
ansible_connection: psrp
ansible_port: 5985
rsat_tools:
  - RSAT-AD-Tools
  - RSAT-AD-PowerShell
  - RSAT-DNS-Server

temp_dir: "C:\\temp"
# Notepad++
npp_url: "https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.9.1/npp.8.9.1.Installer.x64.msi"
npp_msi: "C:\\temp\\npp.8.9.1.Installer.x64.msi"
npp_exe: "C:\\Program Files\\Notepad++\\notepad++.exe"

# KDiff3 (LO4D direct download link provided)
kdiff_url: "https://download.kde.org/stable/kdiff3/kdiff3-1.12.1-windows-x86_64.exe"
kdiff_installer: "C:\\temp\\kdiff3-1.12.1-windows-x86_64.exe"
kdiff_exe: "C:\\Program Files\\KDiff3\\kdiff3.exe"

# windows_installer_install_source_dir: https://download.mozilla.org/?product=firefox-latest&os=win64&lang=en-US
windows_installer_installs:
- install_source_dir: ../files
  install_source_file: Firefox Setup 147.0.4.exe
  files_path: C:\Windows\Temp
  product_id: Mozilla Firefox
  arguments: -ms
  # state: present
- install_source_dir: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.9.1
  install_source_file: npp.8.9.1.Installer.x64.exe
  files_path: C:\Windows\Temp
  product_id: Notepad++
  arguments: /S
  state: absent
