---
- name: Install Notepad++ on Windows
  hosts: all
  tasks:
    - name: Download Notepad++
      ansible.windows.win_get_url:
        url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.9.1/npp.8.9.1.Installer.x64.exe
        dest: C:\Temp\npp.8.9.1.Installer.x64.exe

    - name: Install Notepad++
      ansible.windows.win_package:
        path: C:\Temp\npp.8.9.1.Installer.x64.exe
        product_id: Notepad++
        arguments: '/S'  # /S enables silent installation
        state: present

...
 