# https://github.com/dsccommunity/StorageDsc
volumes:
  db:
    DriveLetter: G
  log:
    DriveLetter: H
  temp:
    DriveLetter: I
    AllowDestructive: true
    Size: 10737418240
  data:
    DriveLetter: J
    FSLabel: CustomDataLabel
